fix secret_name for cf_api_backup_metadata_generator client
cloudfoundry/cf-for-k8s pull request #559
Opened 2020-11-04 00:11 UTC by tcdowney

## WHAT is this change about?
This is a followup PR for a mistake made in https://github.com/cloudfoundry/cf-for-k8s/pull/555.

It includes a pending change to the cf-api-controllers deployment so that this is adequately tested by CI
It is OK if that change is reverted since it will come through via a vendir sync in the future and works fine without it for now.

That can either be done through CI naturally as it bumps to the latest capi-k8s-release or manually while merging this.

## Does this PR introduce a change to `config/values.yml`?
No

## Acceptance Steps
Same as https://github.com/cloudfoundry/cf-for-k8s/pull/555. You should be able to do something like this and see it work after the deploy has succeeded:

```
kubectl exec -n cf-system cf-api-controllers-6cb4d79d5c-z6ntn -c backup-metadata-generator -- "/cnb/process/generate-metadata"
```

CAKE Story: [#175469923](https://www.pivotaltracker.com/story/show/175469923)

2020-11-04 02:18 UTC, davewalter requested changes
Hi @tcdowney,

I managed to get the tests running. Looks like you spotted another bug, but that needs to come in via a bump to capi-k8s-release.

Regards,
Dave

2020-11-05 19:19 UTC, tcdowney commented
@davewalter I actually was waiting to make the capi-k8s-release change until after this was merged since the deploy doesn't succeed without this cf-for-k8s change. I only included that on the PR cause I hoped it would run through the integration tests and see everything pass. The plan was to remove the `config/capi/_ytt_lib/capi-k8s-release/templates/controllers_deployment.yml` change after that happened.

2020-11-05 19:56 UTC, tcdowney commented
I just went ahead and removed it. I tested the deploy locally and it was fine.

2020-11-05 19:56 UTC, tcdowney commented on config/capi/capi.yml
> +      secret_name: cf-api-backup-metadata-generator-client-secret
This needs to match this:
https://github.com/cloudfoundry/cf-for-k8s/pull/559/files#diff-8d0ec3e11b92f104c5b1e83ad6bb3d0bfe0d005b976a1c1b31e29af98690093fR127

2020-11-05 20:32 UTC, davewalter commented
Sorry about that @tcdowney. Our CI is very protective of the component templates we include in cf-for-k8s. We'll get this merged in once the rest of the tests pass.

2020-11-05 21:10 UTC, tcdowney commented
Seems like there is an issue with the external-blobstore tests:
```
Error attaching, falling back to logs: unable to upgrade connection: container minio-client-25f48941698aec50d057e28b not found in pod minio-client-25f48941698aec50d057e28b_default
```

I don't see any reason this would be related, though. 🤔

2020-11-06 00:13 UTC, tcdowney commented
@davewalter do those tests need to provide the `--command` flag to `kubectl run`?

```
kubectl run NAME --image=image [--env="key=value"] [--port=port] [--dry-run=server|client] [--overrides=inline-json]
[--command] -- [COMMAND] [args...] [options]
```

https://github.com/cloudfoundry/cf-for-k8s/blob/c07f67382676420ed6b4204fe166c3cc01944e4b/ci/tasks/run-external-blobstore-validation-test/task.sh#L64

2020-11-06 18:08 UTC, davewalter commented
@tcdowney We had a misconfiguration in our contributions pipeline for this job. It's green now. :)

2020-11-06 18:10 UTC, merged